# GitHub Sponsors configuration for FileForge
# Enable multiple sponsorship platforms

github: koushal13

# These are supported funding model platforms
patreon: # your-patreon-username
open_collective: # your-open-collective-name
ko_fi: # your-ko-fi-username
tidelift: # npm/package-name
community_bridge: # project-name
liberapay: # your-liberapay-username
issuehunt: # your-issuehunt-username
custom: # Add custom sponsorship URLs (e.g., Buy Me a Coffee)
  # - https://www.buymeacoffee.com/yourname
  # - https://paypal.me/yourname
